# footprint: [[ 0.3,  0.3], [-0.3,  0.3], [-0.3, -0.3], [ 0.3, -0.3]]
footprint: [[0.25,0.2],[-0.25,0.2],[-0.25,-0.2],[0.25,-0.2]]
footprint_padding: 0.02
robot_radius: 0.23
#robot_radius: ir_of_robot
inflation_layer:
  inflation_radius: 0.1 # 2xfootprint, it helps to keep the global planned path farther from obstacles
transform_tolerance: 2
