global_costmap:
     update_frequency: 1
     publish_frequency: 1
     transform_tolerance: 0.5
     always_send_full_costmap: false
     width: 50.0
     height: 50.0
     resolution: 0.1
     origin_x: -25.0
     origin_y: -25.0
     plugins:
          - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
          - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
